name: Trigger Release

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'config/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    uses: ./.github/workflows/test.yml

  e2e:
    uses: ./.github/workflows/test-e2e.yml

  trigger-release:
    needs: [lint, tests, e2e]
    if: ${{ success() }}
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release PR
        id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ secrets.RELEASE_GITHUB_PAT }}
          release-type: go
